# Python example
name: deps-audit
on: [push, pull_request]
jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anchore/sbom-action@v0
        with: { path: ., format: spdx-json, output-file: sbom.spdx.json }
      - uses: actions/upload-artifact@v4
        with: { name: sbom, path: sbom.spdx.json }
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt && pip install pip-audit
      - run: pip-audit --strict || true
