name: iac-security
on: [push, pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/tfsec-action@v1.0.3
      - uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
